/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  PocApp as PocApp
} from './components/poc-app/poc-app';

declare global {
  interface HTMLPocAppElement extends PocApp, HTMLElement {
  }
  var HTMLPocAppElement: {
    prototype: HTMLPocAppElement;
    new (): HTMLPocAppElement;
  };
  interface HTMLElementTagNameMap {
    "poc-app": HTMLPocAppElement;
  }
  interface ElementTagNameMap {
    "poc-app": HTMLPocAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "poc-app": JSXElements.PocAppAttributes;
    }
  }
  namespace JSXElements {
    export interface PocAppAttributes extends HTMLAttributes {
      apiUrl?: string;
      environment?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
