/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  PageLanding as PageLanding
} from './components/page-landing/page-landing';

declare global {
  interface HTMLPageLandingElement extends PageLanding, HTMLElement {
  }
  var HTMLPageLandingElement: {
    prototype: HTMLPageLandingElement;
    new (): HTMLPageLandingElement;
  };
  interface HTMLElementTagNameMap {
    "page-landing": HTMLPageLandingElement;
  }
  interface ElementTagNameMap {
    "page-landing": HTMLPageLandingElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "page-landing": JSXElements.PageLandingAttributes;
    }
  }
  namespace JSXElements {
    export interface PageLandingAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  PageOther as PageOther
} from './components/page-other/page-other';

declare global {
  interface HTMLPageOtherElement extends PageOther, HTMLElement {
  }
  var HTMLPageOtherElement: {
    prototype: HTMLPageOtherElement;
    new (): HTMLPageOtherElement;
  };
  interface HTMLElementTagNameMap {
    "page-other": HTMLPageOtherElement;
  }
  interface ElementTagNameMap {
    "page-other": HTMLPageOtherElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "page-other": JSXElements.PageOtherAttributes;
    }
  }
  namespace JSXElements {
    export interface PageOtherAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  PocApp as PocApp
} from './components/poc-app/poc-app';

declare global {
  interface HTMLPocAppElement extends PocApp, HTMLElement {
  }
  var HTMLPocAppElement: {
    prototype: HTMLPocAppElement;
    new (): HTMLPocAppElement;
  };
  interface HTMLElementTagNameMap {
    "poc-app": HTMLPocAppElement;
  }
  interface ElementTagNameMap {
    "poc-app": HTMLPocAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "poc-app": JSXElements.PocAppAttributes;
    }
  }
  namespace JSXElements {
    export interface PocAppAttributes extends HTMLAttributes {
      apiUrl?: string;
      environment?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
